### ISSUE TITLE
How to convert .dat files?

### ISSUE THREAD

**Issue by ZiglioNZ** [goGPS-Project/goGPS_Java#16]
Hi guys!
how's everyone?

I'm logging some real time data to roverOut.data and navigationOut.dat.
That doesn't look like any particular format, it looks to me just java serialization.
Do you know how to convert those files to something more useful, rinex navigation and observation files?
Even better, shouldn't ObservationBuffer produce Rinex files instead of .dat files?

**Comment by ZiglioNZ** [comment]
Oh, I've just found the two examples I was looking for.
One reads from log (.dat) files:

org.gogpsproject.TestReadObsLog

			ObservationsBuffer masterIn = new ObservationsBuffer();
			masterIn.readFromLog(master);

the other one adds a listener to the serialConn class

org.gogpsproject.apps.LogUBX

					rp = new RinexV2Producer(needApproxPos, singleFreq, marker);
					rp.enableCompression(ns.getBoolean("compress"));
					rp.setOutputDir(ns.getString("outdir"));
					ubxSerialConn.addStreamEventListener(rp);
 
I like the second way I think I'm gonna use it.
I still don't get why we need log files, wouldn't Rinex be enough?
It seems an unneeded extra set.
I hope to release a new version of the GUI this week

**Comment by ege010** [comment]
Hi Emanuele,

those .dat files were introduced by CRYMS, when goGPS Java still lacked a RINEX file writing function :)
I've not used them recently, I agree with you that writing RINEX file is generally enough... unless one has storage space limitations, but in that case one could store just the original binary file (e.g. UBX stream, RTCM stream, etc).

**Comment by ZiglioNZ** [comment]
Well at least there's a historical reason!
If nobody uses them, we could perhaps remove them.

**Comment by ege010** [comment]
We could definitely remove them. Better check the repercussions throughout the software, though!

**Comment by ZiglioNZ** [comment]
That answers my question, thank you
