### ISSUE TITLE
A truly modular design (refactoring ReceiverPosition)

### ISSUE THREAD

**Issue by ZiglioUK** [goGPS-Project/goGPS_Java#17]
I don't know about goGPS Matlab but in the Java version there's a lot of copy&paste.
It's true that the design of goGPS is modular but that is not reflected in the code: each module basically   copies and extends another one.
That makes it very easy to read, but harder to maintain because when something changes, all those copies have to change too.
Perhaps we could create a branch called "modular redesign" and experiment there, what do you guys think?

**Comment by ege010** [comment]
I agree with you, we need to remove or at least reduce the redundant code.
Please go on with the branch!

2015-10-26 22:20 GMT+01:00 Emanuele Ziglioli <notifications@github.com>:

**Comment by ZiglioNZ** [comment]
Some thoughts, after using Java 8 for the past month, I got to love lambdas and related APIs such as Function and Supplier.

I can see ReceiverPosition evolving into a functional type of class, where we can pass functionality that can be composed. Even with old Java 7, we could change the API to be:

ReceiverPosition( CodeFunction )
ReceiverPosition( CodeFunction, CodePhase )
ReceiverPosition( CodeFunction, Kalman )
ReceiverPosition( CodeFunction, CodePhase, Kalman )
...

with each "supplier" providing the ability to add rows and columns to the matrix A, for example they could implement an interface:
Matrix mtxSupplier( Matrix A)

Not sure yet whether they should operate on the whole matrix or on either rows or columns or both.

**Comment by ZiglioNZ** [comment]
I've started some refactoring work.
First steps:
1. Move ReceiverPosition to a new package (core, or positioning if you prefer)
2. Start splitting the individual algorithms into separate classes. I'll try to follow the Matlab version naming conventions but I don't know that code very well, so please feel free to provide any suggestion

This change will affect the "troposphere" branch but it should be reasonably easy to merge changes from that branch manually

**Comment by ZiglioNZ** [comment]
Here we go: https://github.com/goGPS-Project/goGPS_Java/commit/dce1a9ef6ebf7f990f4e3c4173ffd36658771e8b

**Comment by ZiglioNZ** [comment]
Ok, I've broken it! by refactoring the "state" (like SatellitePosition[] pos) out of ReceiverPosition, I've now got a duplication of that state that is currently not shared.
So if we call first selectSatellites(), then KalmanFilter.init(), the SatellitePosition array is inside the first object, not the second. So please bear with me, and don't use it yet, because it doesn't work :-/

**Comment by ZiglioNZ** [comment]
All done -> https://github.com/goGPS-Project/goGPS_Java/commit/843f5ad6cf726e83079e929a98bbb8b132ed904e

Tested by y running TestGoGPS.main() in different modes
