### ISSUE TITLE
Use fluent API

### ISSUE THREAD

**Issue by ZiglioNZ** [goGPS-Project/goGPS_Java#23]
Simple change, make all setters "return this;" so we can chain initialization, for example:

```
goGPS = GoGPS.create(navigationIn, roverIn, masterIn) 
  .addPositionConsumerListener(kml) 
  .setDynamicModel(dynamicModel);
```

instead of

```
goGPS = new GoGPS(navigationIn, roverIn, masterIn); 
goGPS.addPositionConsumerListener(kml); 
goGPS.setDynamicModel(dynamicModel);
```

**Comment by ege010** [comment]
Would be very nice!
Questa e-mail è stata inviata da un computer privo di virus protetto da
Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-02-02 22:00 GMT+01:00 Emanuele Ziglioli <notifications@github.com>:

**Comment by ZiglioNZ** [comment]
https://github.com/goGPS-Project/goGPS_Java/commit/e0cd980f28eac65bb93e6bac5b6e8044f03d8d2b
