### ISSUE TITLE
Message type  in RTCMClient

### ISSUE THREAD

**Issue by lazicsasalaki** [goGPS-Project/goGPS_Java#24]
Dear Colleagues,

I am using goGPS and trying to read messages type 1015,1016,1017 from RTCM 3 mountpoint.

However I am only receiving messages type  1004,1012, 1019, 1020 and other even though the mountpoint is setup to send message types state above.

In RTCMClient.java there is condition 

if (c == 211) { // header
readMessage(in);
}

Which is used to determine the start of message (header).

Can you please tell me why is character code 211 being used for this condition and does is apply also to the messages I am trying to read ?

Do you have any idea how to catch these messages ? 

Any suggestion / advised would be helpful

Thanks in advance

**Comment by ZiglioNZ** [comment]
Can't help, haven't used RTCM yet. But I'm glad to see someone else using goGPS/Java!
Pinging @ege010 @nro2dai

**Comment by ege010** [comment]
Hi,

the first byte in any RTCM message should be equal to 211. In the RTCM3
documentation it is reported that the transport layer starts with the
preamble 11010011

>> bin2dec('11010011')

ans =

   211

As for catching messages 1015, 1016, 1017, it would be needed to write
parsers for those messages and add them to org.gogpsproject.parser.rtcm3,
then call them from RTCM3Client.java. In fact, at the moment goGPS Java has
parsers only for messages 1004, 1005, 1006, 1007, 1008 and 1012
https://github.com/goGPS-Project/goGPS_Java/tree/master/src/main/java/org/gogpsproject/parser/rtcm3

As an alternative, you could use goGPS MATLAB, that has all the RTCM3
messages you need already implemented:
https://github.com/goGPS-Project/goGPS_MATLAB/tree/master/goGPS/input_output/RTCM

In case you could also use goGPS MATLAB files just as a reference to
implement the Java ones.

Eugenio

P.S. I'm going to be out of office from tomorrow to June 12, so in case I
will catch up with the discussion in the second half of June (unless I
manage to read work emails before then ;) )

**Comment by lazicsasalaki** [comment]
Thanks So much, I am decoding , perfect

**Comment by ege010** [comment]
Thanks to you for using goGPS!
