### ISSUE TITLE
Position validation of UBX files?

### ISSUE THREAD

**Issue by MartaBanach** [goGPS-Project/goGPS_Java#32]
I have a few ubx rawx files, but some of them seem not to work with goGPS, even after your recommendations (https://github.com/goGPS-Project/goGPS_Java/issues/27). The result is: 
"Valid LS position? false Coord ECEF: X:0.0 Y:0.0 Z:0.0
ENU: E:0.0 N:0.0 U:0.0
GEOD: Lon:0.0 Lat:0.0 H:0.0"
I thought that some of them may be too short, but now I see that's not the case. I tried to parse and compare satellite data from different files with my own C# app, but I cannot see what is causing the problem. What makes a position valid? Can you identify any problems with these files?
I'm attaching a file that processes successfully and one that fails.

[rawx.zip](https://github.com/goGPS-Project/goGPS_Java/files/912733/rawx.zip)

**Comment by ZiglioNZ** [comment]
hi @MartaBanach , 

see i32() in https://github.com/goGPS-Project/goGPS_Java/blob/master/src/test/java/com/github/Issues.java

I can only run it in Standalone mode.
Am I missing some other files?
[failOut_Standalone.zip](https://github.com/goGPS-Project/goGPS_Java/files/914772/failOut_Standalone.zip)

**Comment by MartaBanach** [comment]
I've also run those three files in Standalone Mode and got exactly the same result – an empty kml file without any position. Still haven’t discovered why these files are not working.

**Comment by ZiglioNZ** [comment]
Hi again @MartaBanach 

apologies, I think the problem was once again that producers run in different threads, so we have to wait for them to finish at the end.

```
        GoGPS goGPS = new GoGPS(navigationIn, roverIn );
        RoverPosition roverPos = goGPS
                                     .addPositionConsumerListener(kml)
                                     .setDynamicModel(dynamicModel)
                                     .setCutoff(0)
                                     .runCodeStandalone();
        goGPS.runUntilFinished();

```

Also I had introduced a little problem yesterday that hopefully is now fixed.
Please check out the latest code and see files in attachment
[FailKMLs.zip](https://github.com/goGPS-Project/goGPS_Java/files/920856/FailKMLs.zip)

**Comment by MartaBanach** [comment]
Thank you once again for your help.
