### ISSUE TITLE
Kalman dops

### ISSUE THREAD

**Issue by ZiglioUK** [goGPS-Project/goGPS_Java#33]
Question for @ege010 , any special reason why there's a set of dops specific to the Kalman Filter?
See [RoverPosition](https://github.com/goGPS-Project/goGPS_Java/blob/master/src/main/java/org/gogpsproject/positioning/RoverPosition.java):

	/** Kalman-derived position dilution of precision (KPDOP) */
	double kpDop; 
	
	/** Kalman-derived horizontal dilution of precision (KHDOP) */
	double khDop; 
	
	/** Kalman-derived vertical dilution of precision (KVDOP) */
	double kvDop; 

Also, do we need a dopType?

```
  private int dopType = DOP_TYPE_NONE;
  public final static int DOP_TYPE_NONE = 0;
  public final static int DOP_TYPE_STANDARD = 1; /* Standard DOP values (satellite geometry only) */
  public final static int DOP_TYPE_KALMAN = 2; /* Kalman DOP values (KDOP), based on the Kalman filter error covariance matrix */

```

**Comment by ege010** [comment]
It was a feature we introduced for a specific study we carried out some years ago with @nro2dai : 
https://www.researchgate.net/publication/256841864_Integrating_low-cost_RTK_positioning_services_with_a_web-based_track_log_management_system

They are not really standard, but it could be useful to have indices that summarize the Kalman filter estimation error.

**Comment by ZiglioNZ** [comment]
Ok, we'd better keep it then.

Another question: why is a special [Adop matrix](https://github.com/goGPS-Project/goGPS_Java/blob/master/src/main/java/org/gogpsproject/positioning/LS_DD_code.java) for dop computation is created for the LS_DD_code case but not for other DD cases?

**Comment by ege010** [comment]
That's a good question! :)
We should check which approach is correct, i.e. whether to include the pivot component or not...
