### ISSUE TITLE
Consider renaming this project to goGPS_Java (or similar)

### ISSUE THREAD

**Issue by ZiglioNZ** [goGPS-Project/goGPS_Java#4]
Let's make room for goGPS Matlab :-)
Also, I don't know whether there's a tool to export SVN history from Sourceforge to Git. I've used Git-svn in the past, it's supported by Git's command line.
Not easy to use, it does work though

**Comment by ege010** [comment]
You are right, it would be nice to make room for goGPS MATLAB... better be prepared for the future!
What do you think @nro2dai ?

**Comment by nro2dai** [comment]
agree!

2015-06-23 18:40 GMT+09:00 Eugenio Realini <notifications@github.com>:

**Comment by ege010** [comment]
Done!
